---
title: "Inspection Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(httr)
library(jsonlite)
library(plotly)
```

```{r, include=FALSE}
get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/43nn-pn8j.json"

nyc_inspections = 
  get_all_inspections(url) %>%
  bind_rows() %>% 
  filter(boro == "Manhattan", critical_flag == "Critical", score %in% 0:13, cuisine_description == "American")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A - relationship between street and score

```{r}
nyc_inspections %>% 
   mutate(
     score = as.numeric(score),
     text_label = str_c("Restaurant: ", dba)
  ) %>% 
  plot_ly(
    x = ~street, y = ~score, color = ~street,
    type = "scatter", mode = "markers",
    alpha = .3, text = ~text_label, colors = "viridis"
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B - score of different violation codes

```{r}
nyc_inspections %>% 
  mutate(score = as.numeric(score), violation_code = fct_reorder(violation_code, score)) %>% 
  plot_ly(
    y = ~score, color = ~violation_code,
    type = "box", colors = "viridis"
  )
```

### Chart C - count of restaurants in council district

```{r}
nyc_inspections %>% 
  count(council_district) %>% 
  mutate(council_district = fct_reorder(council_district, n)) %>% 
  plot_ly(x = ~council_district, y = ~n, color = ~council_district, type = "bar", colors = "viridis")
```

